### ISSUE TITLE
回答用のモーダル

### ISSUE THREAD

**Issue by cn-eveer** [yuji96/slack-app-when#16]
[回答モーダル](https://app.slack.com/block-kit-builder/T0277BHM69J#%7B%22type%22:%22modal%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E6%99%82%E9%96%93%E8%AA%BF%E6%95%B4%E3%81%AE%E5%9B%9E%E7%AD%94%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E6%8F%90%E5%87%BA%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E3%82%84%E3%82%81%E3%82%8B%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%7Bdate%7D*%20%E3%81%AE%E5%8F%AF%E8%83%BD%E3%81%AA%E6%99%82%E9%96%93%22%7D,%22accessory%22:%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22,%22action_id%22:%22button-action%22%7D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22timepicker%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%A7%8B%E6%99%82%E9%96%93%22,%22emoji%22:true%7D,%22action_id%22:%22actionId-0%22%7D,%7B%22type%22:%22timepicker%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E7%B5%82%E4%BA%86%E6%99%82%E9%96%93%22,%22emoji%22:true%7D,%22action_id%22:%22actionId-1%22%7D,%7B%22type%22:%22checkboxes%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E7%B5%82%E6%97%A5%E9%80%B1%E5%8F%AF%E8%83%BD%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D%5D,%22action_id%22:%22actionId-5%22%7D%5D%7D%5D%7D)

ホストが作ったモーダルから値を取るのは厳しそう、ホストが送ったメッセージでしか値が取得できない状態。逆も然り、メンバーが回答したモーダルをメッセージにしてそこから値を取るほか今の方法しかない。

**Comment by yuji96** [comment]
アンケートの回答は`12:00-14:00, 15:00-17:00`のように1日の中で時間帯が分かれる可能性があり、datetime picker がだと限界がありそうなので plain_text input の想定でした。

**Comment by yuji96** [comment]
- [`plain_text_input`の場合のモーダル](https://app.slack.com/block-kit-builder/T030HT2GU#%7B%22type%22:%22modal%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%20%22%7D,%22accessory%22:%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%A7%E5%9B%9E%E7%AD%94%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22,%22action_id%22:%22button-action%22%7D%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22ex%29%201100-1300,%201530-1600%22%7D%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22date%20time%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22ex%29%201100-1300,%201530-1600%22%7D%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22date%20time%22,%22emoji%22:true%7D%7D%5D%7D)

- `timepicker`の場合は以下のレイアウトが上手くできないので保留
  - 終日可能や終日不可能のボタンの設置
  - 時間帯の追加・削除ボタン
  - スマホだと全ての要素が1列に並ぶので時間帯が2つ以上あると1日でも1画面に入りきらない。
