### ISSUE TITLE
管理者 ミーティング設定モーダル

### ISSUE THREAD

**Issue by yuji96** [yuji96/slack-app-when#2]
[回答モーダル](https://app.slack.com/block-kit-builder/T0277BHM69J#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%E6%97%A5%E7%A8%8B%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%BE%E3%81%A7%E3%81%AE%E9%96%93%E3%81%AB%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E5%8F%AF%E8%83%BD%E3%81%AA%E6%99%82%E9%96%93%E5%B8%AF%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2213:37%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%AE%E9%96%93%E3%81%AE%E3%81%A9%E3%81%93%E3%81%8B%E3%81%A7%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2213:37%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E8%80%85%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%20%22%7D,%22accessory%22:%7B%22type%22:%22multi_conversations_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20conversations%22,%22emoji%22:true%7D,%22action_id%22:%22multi_conversations_select-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E6%9C%9F%E9%99%90%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22actionId-0%22%7D,%7B%22type%22:%22timepicker%22,%22initial_time%22:%2213:37%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%5D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22radio_buttons%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E6%9C%AA%E5%9B%9E%E7%AD%94%E8%80%85%E3%81%AB%E6%9C%9F%E9%99%90%20*1%E6%99%82%E9%96%93%E5%89%8D*%20%E3%81%AB%E3%83%A1%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3%22%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E6%9C%AA%E5%9B%9E%E7%AD%94%E8%80%85%E3%81%AB%E6%9C%9F%E9%99%90%20*1%E6%97%A5%E5%89%8D*%20%E3%81%AB%E3%83%A1%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3%22%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E3%83%A1%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%97%E3%81%AA%E3%81%84%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D%5D,%22action_id%22:%22actionId-0%22%7D%5D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E3%81%AE%E5%85%AC%E9%96%8B%E7%AF%84%E5%9B%B2%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22radio_buttons%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E4%B8%BB%E5%82%AC%E8%80%85%E3%81%A0%E3%81%91%E3%81%AB%E5%9B%9E%E7%AD%94%E3%82%92%E9%80%81%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB%E3%81%AB%E5%85%A8%E5%93%A1%E3%81%AE%E5%9B%9E%E7%AD%94%E3%82%92%E5%85%AC%E9%96%8B%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22value-1%22%7D%5D,%22action_id%22:%22actionId-0%22%7D%5D%7D%5D%7D)

**Comment by yuji96** [comment]
セレクトボックスの値によって画面が切り替えられるみたいだから一度に表示する項目減らせそう
https://qiita.com/seratch/items/9b5666479ad9f602e5ee

**Comment by cn-eveer** [comment]
[個人](https://app.slack.com/block-kit-builder/T0277BHM69J#%7B%22type%22:%22modal%22,%22callback_id%22:%22set_schedules-im%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E6%99%82%E9%96%93%E8%AA%BF%E6%95%B4%22%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%89%E3%81%98%E3%82%8B%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%E6%97%A5%E7%A8%8B%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22start_date%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22end_date%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%BE%E3%81%A7%E3%81%AE%E9%96%93%E3%81%AB%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E5%8F%AF%E8%83%BD%E3%81%AA%E6%99%82%E9%96%93%E5%B8%AF%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22start_time%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2206:00%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22end_time%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%BE%E3%81%A7%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2223:00%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E3%81%AE%E5%85%AC%E9%96%8B%E7%AF%84%E5%9B%B2%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22input%22,%22block_id%22:%22users_select%22,%22element%22:%7B%22type%22:%22multi_users_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20target%20Users%22,%22emoji%22:true%7D,%22action_id%22:%22multi_users_select-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%20%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E3%81%AE%E5%85%AC%E9%96%8B%E7%AF%84%E5%9B%B2%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22input%22,%22block_id%22:%22display_result%22,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%20%22,%22emoji%22:true%7D,%22element%22:%7B%22type%22:%22radio_buttons%22,%22action_id%22:%22result-option%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E4%B8%BB%E5%82%AC%E8%80%85%E3%81%A0%E3%81%91%E3%81%AB%E5%9B%9E%E7%AD%94%E3%82%92%E9%80%81%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22host%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E8%80%85%E3%81%AB%E5%85%A8%E5%93%A1%E3%81%AE%E5%9B%9E%E7%AD%94%E3%82%92%E5%85%AC%E9%96%8B%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22all%22%7D%5D%7D%7D%5D%7D)

[チャンネル](https://app.slack.com/block-kit-builder/T0277BHM69J#%7B%22type%22:%22modal%22,%22callback_id%22:%22set_schedules-channel%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E6%99%82%E9%96%93%E8%AA%BF%E6%95%B4%22%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%89%E3%81%98%E3%82%8B%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%E6%97%A5%E7%A8%8B%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22start_date%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22end_date%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%97%A5%E3%81%BE%E3%81%A7%E3%81%AE%E9%96%93%E3%81%AB%E9%96%8B%E5%82%AC%E3%81%97%E3%81%9F%E3%81%84%22%7D,%22accessory%22:%7B%22type%22:%22datepicker%22,%22initial_date%22:%221990-04-28%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20date%22,%22emoji%22:true%7D,%22action_id%22:%22datepicker-action%22%7D%7D,%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E9%96%8B%E5%82%AC%E5%8F%AF%E8%83%BD%E3%81%AA%E6%99%82%E9%96%93%E5%B8%AF%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22start_time%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%8B%E3%82%89%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2206:00%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22end_time%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E3%81%93%E3%81%AE%E6%99%82%E5%88%BB%E3%81%BE%E3%81%A7%22%7D,%22accessory%22:%7B%22type%22:%22timepicker%22,%22initial_time%22:%2223:00%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20time%22,%22emoji%22:true%7D,%22action_id%22:%22timepicker-action%22%7D%7D,%7B%22type%22:%22input%22,%22block_id%22:%22channel_select%22,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E8%80%85%22,%22emoji%22:true%7D,%22element%22:%7B%22type%22:%22channels_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20target%20Channel%22,%22emoji%22:true%7D%7D%7D,%7B%22type%22:%22input%22,%22block_id%22:%22display_result%22,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E3%81%AE%E5%85%AC%E9%96%8B%E7%AF%84%E5%9B%B2%22,%22emoji%22:true%7D,%22element%22:%7B%22type%22:%22radio_buttons%22,%22action_id%22:%22result-option%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E4%B8%BB%E5%82%AC%E8%80%85%E3%81%A0%E3%81%91%E3%81%AB%E5%9B%9E%E7%AD%94%E3%82%92%E9%80%81%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22host%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB%E3%81%AB%E5%85%A8%E5%93%A1%E3%81%AE%E5%9B%9E%E7%AD%94%E3%82%92%E5%85%AC%E9%96%8B%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22value%22:%22all%22%7D%5D%7D%7D%5D%7D)
