### ISSUE TITLE
参加者 回答用メッセージ

### ISSUE THREAD

**Issue by yuji96** [yuji96/slack-app-when#3]
[回答モーダル](https://app.slack.com/block-kit-builder/T030HT2GU#%7B%22blocks%22:%5B%7B%22dispatch_action%22:true,%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22dispatch_action_config%22:%7B%22trigger_actions_on%22:%5B%22on_character_entered%22%5D%7D,%22action_id%22:%22plain_text_input-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%222020-12-23%22,%22emoji%22:true%7D%7D%5D%7D)

[~~確認モーダル~~](https://app.slack.com/block-kit-builder/T030HT2GU#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%60%60%60%20%20%20%20%20%20%20%20%20%20%206%20%207%20%208%20...%5Cn2021-05-03%20%7C%20%20%7C##%7C%20...%20%20%60%60%60%22%7D%7D%5D%7D)

**Comment by yuji96** [comment]
ビジネス用のチャンネルではプロジェクトメンバーの他にバックオフィスの方がいたりするから、回答拒否機能が必要。回答拒否した場合も管理者にbotが通知する。

**Comment by yuji96** [comment]
モーダルよりもメッセージに埋め込んだ方がリアクションの速度上がりそう

**Comment by cn-eveer** [comment]
回答対象者向けのメッセージ
[request_message.json](https://app.slack.com/block-kit-builder/T0277BHM69J#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E6%99%82%E9%96%93%E8%AA%BF%E6%95%B4%E3%81%AE%E3%81%94%E5%8D%94%E5%8A%9B%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22to%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%5Cn%E4%BB%A5%E4%B8%8B%E3%81%AE%E5%86%85%E5%AE%B9%E3%81%A7%E6%99%82%E9%96%93%E8%AA%BF%E6%95%B4%E3%82%92%E8%A1%8C%E3%81%84%E3%81%BE%E3%81%99%E3%80%82%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22host%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%E4%B8%BB%E5%82%AC%E8%80%85:*%5Cn%3C@test-user%3E%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22date%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%E9%96%8B%E5%82%AC%E6%97%A5:*%5Cn2021-07-10%20%E3%81%8B%E3%82%89%202021-07-11%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22time%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%E9%96%8B%E5%82%AC%E6%99%82%E9%96%93:*%5Cn06:00%20%E3%81%8B%E3%82%89%2023:00%22%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22setting%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%E5%9B%9E%E7%AD%94%E8%A8%AD%E5%AE%9A:*%5Cn%E4%B8%BB%E5%82%AC%E8%80%85%E3%81%A0%E3%81%91%E3%81%AB%E5%9B%9E%E7%AD%94%E3%82%92%E9%80%81%E3%82%8B%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%8F%82%E5%8A%A0%E3%81%A7%E3%81%8D%E3%82%8B%E6%99%82%E9%96%93%E3%82%92%E3%81%8A%E7%AD%94%E3%81%88%E4%B8%8B%E3%81%95%E3%81%84%22%7D,%22accessory%22:%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%E5%9B%9E%E7%AD%94%E3%81%99%E3%82%8B%22,%22emoji%22:true%7D,%22style%22:%22primary%22,%22value%22:%22answer-schedule%22,%22action_id%22:%22answer-schedule%22%7D%7D%5D%7D)
